// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package storage

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Stop struct {
	StopID       string
	StopName     string
	StopLat      pgtype.Numeric
	StopLon      pgtype.Numeric
	LocationType pgtype.Int2
}
