name: Autobuild and package

on:
  push:
    branches:
      - master

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: europe-west3-a
  GKE_CLUSTER: ab-cluster-1
  IMAGE_BASE: eu.gcr.io/${{ secrets.GKE_PROJECT }}/ioe/senseview

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      # Setup gcloud CLI
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: '270.0.0'
          service_account_email: ${{ secrets.GKE_EMAIL }}
          service_account_key: ${{ secrets.GKE_KEY }}

      # Configure docker to use the gcloud command-line tool as a credential helper
      - name: GCloud Auth
        run: |
          # Set up docker to authenticate
          # via gcloud command-line tool.
          gcloud auth configure-docker

      # Build the Docker images
      - name: Build
        run: |
          docker build -t "$IMAGE_BASE"/senseview-ui:"$GITHUB_SHA" \
            --build-arg GITHUB_SHA="$GITHUB_SHA" \
            --build-arg GITHUB_REF="$GITHUB_REF" \
            .

      # Push the Docker images to Google Container Registry
      - name: Publish
        run: |
          docker push "$IMAGE_BASE"/senseview-ui:"$GITHUB_SHA"
          docker tag "$IMAGE_BASE"/senseview-ui:"$GITHUB_SHA" "$IMAGE_BASE"/senseview-ui:latest
          docker push "$IMAGE_BASE"/senseview-ui:latest
