name: Build and Deploy to GKE

on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: europe-west3-a
  GKE_CLUSTER: ab-cluster-1
  IMAGE_BASE: eu.gcr.io/${{ secrets.GKE_PROJECT }}/gtfs
  GO111MODULE: on
  CGO_ENABLED: 0

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - run: go test ./...

    - run: go build -o bin/main cmd/main.go


    # Build the Docker images
    - name: Build Core
      run: |
        docker build -t "$IMAGE_BASE"/go-gtfs-query-api:"$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          -f Dockerfile .

    - name: 'Authenticate with GKE'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GKE_KEY }}'

      # Setup gcloud CLI
    - name: 'Set up gcloud SDK'
      uses: google-github-actions/setup-gcloud@v1
      with:
        install_components: 'gke-gcloud-auth-plugin'

    - name: 'GCloud Authenticate Docker'
      run: gcloud auth configure-docker europe-west3-docker.pkg.dev


    # Push the Docker images to Google Container Registry
    - name: Publish
      run: |
        docker tag "$IMAGE_BASE"/go-gtfs-query-api:"$GITHUB_SHA" "$IMAGE_BASE"/go-gtfs-query-api
        docker push "$IMAGE_BASE"/go-gtfs-query-api:"$GITHUB_SHA"
        docker push "$IMAGE_BASE"/go-gtfs-query-api
